In [1]:
import pandas as pd

In [9]:
data = pd.read_excel("annotation_n1000_samples_500.xlsx")

In [60]:
sampled_data_500 = data[:501]
sampled_data_500

,id,thumbnail,summary,Q1,Q2,Q3,Q3a,Q4,Q4a
0,1078928,NaN,Scotland was defeated 2-0 by the Czech Republi...,1.0,"Scotland, Wembley, Hampden Park, Czech Republic,",1.0,Hampden Park,0.0,"Czech Republic, Scotland"
8,1852607,NaN,"Despite the challenges of the pandemic, netbal...",1.0,"netball, comeback, Superleague season, profess...",1.0,netball,0.0,Superleague season
16,1553382,NaN,Patrick Bamford's impressive performance for L...,1.0,"Patrick Bamford, impressive performance, Leeds...",1.0,Patrick Bamford,0.0,key players' performances
43,2812283,NaN,Hebei province in China is on lockdown after e...,1.0,"Hebei province in China, lockdown, coronavirus...",1.0,coronavirus cases,0.0,"quarantine measures, lockdown"
72,1189759,NaN,An Indiana business is offering pole dancing l...,1.0,"An Indiana business, pole dancing lessons , ch...",1.0,"children, pole dancing lessons",0.0,registered sex offender
78,2100987,NaN,Certain conservative Democrats are threatening...,1.0,"Democrats, President Biden, infrastructure bil...",1.0,President Biden,0.0,Democrats
119,2161755,NaN,Despite warnings to avoid travel after a snows...,1.0,"travel, snowstorm, drivers, highways, Google M...",1.0,stranded vehicles,0.0,snowstorm
121,1810655,NaN,President Biden paid his respects to fallen po...,1.0,"President Biden, respects, police officers, Na...",1.0,"President Biden, police officers",0.0,National Peace Officers' Memorial Service
162,1578897,NaN,"After 40 years, the Swedish pop quartet Abba h...",1.0,"the Swedish pop quartet, Abba, a new album of...",1.0,Abba,0.0,digital version
165,1475286,NaN,Hospitals and ambulance services are facing a ...,1.0,"Hospitals, ambulance, crisis, surge, Covid-19 ...",1.0,ambulance,0.0,Hospitals
191,1328319,NaN,The article discusses the events of January 6t...,1.0,"events of January 6th, the U.S. Capitol, the ...",1.0,attack on the U.S. Capitol,0.0,"insurrection, riot"
192,1102254,NaN,Australia triumphed in the T20 World Cup final...,1.0,"Australia, T20 World Cup final, Mitchell Marsh...",1.0,"Australia, T20 World Cup final, Mitchell Marsh",0.0,victory
194,1877823,NaN,The article highlights the best Black Friday d...,1.0,"the best Black Friday, Dyson products, vacuum ...",1.0,vacuum cleaners,0.0,Dyson products
206,1093391,NaN,Liverpool's Sadio Mane scored his 100th goal f...,1.0,"Liverpool, Sadio Mane, goal, club, Premier Lea...",1.0,Sadio Mane,0.0,win
207,1809747,NaN,Employer vaccine mandates are sparking debate ...,1.0,"Employer vaccine mandates, debate, faith-based...",1.0,faith-based exemptions,0.0,Employer vaccine mandates
210,1106038,NaN,Staff at 10 Downing Street are reported to hav...,1.0,"Staff, 10 Downing Street, Christmas party, loc...",1.0,10 Downing Street,0.0,Christmas party
214,1667964,NaN,Kevin Durant has signed a second contract with...,1.0,"Kevin Durant, second contract, Nets, strong te...",1.0,"Kyrie Irving, Kevin Durant",0.0,"teammate, strong team"
225,1587698,NaN,The article highlights the contrasting views o...,1.0,"views, Prime Minister Boris Johnson, 95-year-o...",1.0,Prime Minister Boris Johnson,0.0,sincerity
229,1313322,NaN,"Grant Shapps, the Transport Secretary, had a m...",1.0,"Grant Shapps, Transport Secretary, minor opera...",1.0,Grant Shapps,0.0,good spirits
233,1439674,NaN,Fans of Doctor Who were devastated by the depa...,1.0,"Fans, Doctor Who, departure, Bradley Walsh, To...",1.0,"Bradley Walsh, Tosin Cole",0.0,Doctor Who
236,2839108,NaN,The University of North Carolina at Chapel Hil...,0.0,"University, North Carolina, Chapel Hill, vote,...",1.0,Nikole Hannah-Jones,0.0,NaN
238,1802072,NaN,Louisiana will continue to use expanded absent...,1.0,"Louisiana, expanded absentee-by-mail voting, s...",1.0,vote,0.0,"absentee ballot,"
240,1250291,NaN,The article discusses the intense fighting in ...,1.0,"fighting, Afghanistan, Lashkar Gah city, impac...",1.0,conflict,0.0,Afghanistan
247,1241412,NaN,A breakdown in Pakistan's national power grid ...,1.0,"Breakdown, Pakistan's national power grid, cou...",1.0,countrywide blackout,0.0,Breakdown
249,1102291,NaN,"Australia thrashed New Zealand in cricket, tha...",1.0,"Australia, thrashing, New Zealand, cricket, pe...",1.0,"Josh Hazlewood, Mitch Marsh",0.0,Australia
257,1875846,NaN,The article discusses the murder mystery and p...,1.0,"Murder mystery, police investigation, TV show ...",1.0,TV show Hollington Drive,0.0,suburban sisters
258,1414853,NaN,AMC has expanded open captioning to 240 cinema...,0.0,"AMC, open captioning, 240 cinemas, US, select ...",1.0,"AMC, theaters",0.0,NaN
263,2083288,NaN,President Biden fired the commissioner of Soci...,0.0,"President Biden, commissioner, Social Security...",1.0,"Andrew Saul,",0.0,Capitol Hill
264,1474522,NaN,The investigation into the assassination of in...,1.0,"Investigation, assassination, investigative jo...",1.0,Daphne Caruana Galizia,0.0,"Investigation, assassination"
269,1099027,NaN,Frances Haugen spoke to MPs about her findings...,1.0,"Frances Haugen, MPs, findings, Facebook's rese...",1.0,"Frances Haugen,",0.0,MPs
271,1069974,NaN,"Grimes, the singer and producer, has unveiled ...",1.0,"Grimes, singer, producer, sprawling full back ...",1.0,"beautiful alien scars, 18 tattoos",0.0,artistic meanings
273,1589938,NaN,"Priti Patel, the UK Home Secretary, has propos...",0.0,"Priti Patel, UK Home Secretary, inhumane meas...",1.0,Priti Patel,0.0,discourage
291,1589294,NaN,"The UK government, including Boris Johnson, ha...",1.0,"UK government, Boris Johnson, shift, position,...",1.0,Parthenon marbles,0.0,"Greece, British Museum trustees"
294,1113691,NaN,The article explores the Guardian's coverage o...,1.0,"Guardian's coverage, US political history, pas...",1.0,"Guardian's coverage, Abraham Lincoln,",0.0,past 200 years
299,2151934,NaN,Kohl's is offering a variety of discounts as p...,1.0,"Kohl's, discounts, Wow Deals, 60%, bedding, pi...",1.0,"home essentials,",0.0,"Wow Deals,"
300,1442923,NaN,Leicester's impressive performance under Brend...,1.0,"Leicester, performance, Brendan Rodgers, victo...",1.0,Chelsea,0.0,victory
303,1481028,NaN,A 60-year-old man died while hiking in Death V...,1.0,"60-year-old man, Death Valley National Park, t...",1.0,"Death Valley National Park,",0.0,precautions
305,2693064,NaN,CNN welcomed back Jeffrey Toobin after a seven...,1.0,"CNN, Jeffrey Toobin, seven-month absence, scan...",1.0,"CNN, Jeffrey Toobin",0.0,seven-month absence
310,1479162,NaN,A woman used social media to call out a party ...,1.0,"woman, social media, party bus company, discri...",1.0,"woman, social media,",0.0,"party bus company,"
317,1255046,NaN,At least 13 people were killed and many others...,1.0,"People, Mount Semeru, eruption, island, Java, ...",1.0,People,0.0,Mount Semeru
323,1498354,NaN,Jenson Button believes that the Formula 1 titl...,1.0,"Jenson Button, Formula 1, title race, Lewis Ha...",1.0,"Jenson Button, Lewis Hamilton,",0.0,"Saudi Grand Prix,"
326,1854499,NaN,Liverpool ended their losing streak with a win...,1.0,"Liverpool, streak, win, Sheffield United, Klop...",1.0,"Liverpool, Sheffield United",0.0,win
327,1055589,NaN,There are a variety of smartwatches and fitnes...,1.0,"Smartwatches, fitness trackers, features, stre...",1.0,fitness trackers,0.0,health
334,1070642,NaN,Norwich City's promotion to the Premier League...,1.0,"Norwich City, promotion, Premier League, confi...",1.0,"Norwich City,",0.0,victory
338,1144157,NaN,The Los Angeles Zoo has reopened with limited ...,1.0,"Los Angeles Zoo, reopened, limited capacity, s...",1.0,"visitors, social distancing measures",0.0,"Los Angeles Zoo,"
340,1668556,NaN,"Netflix's co-CEO, Ted Sarandos, has shown cour...",1.0,"Netflix's co-CEO, Ted Sarandos, courage, refus...",1.0,"Ted Sarandos,",0.0,cancel culture
357,1432592,NaN,Relentless wind and rain have caused tornadoes...,1.0,"Relentless wind, rain, tornadoes, flash floods...",1.0,widespread damage,0.0,tornadoes
358,1312555,NaN,Anyone who has received the Pfizer or Moderna ...,1.0,"Pfizer, Moderna, COVID-19 vaccine, six months ...",1.0,COVID-19,0.0,"Pfizer, Moderna"
385,1315621,NaN,"Jane Lynch, known for her skill in finding pre...",1.0,"Jane Lynch, skill, finding precious objects, s...",1.0,Jane Lynch,0.0,Mick Haddock's lost wedding ring
432,2646746,NaN,The article discusses Harriet Tubman's efforts...,1.0,"Harriet Tubman, Underground Railroad, Black Am...",1.0,Harriet Tubman,0.0,Black Americans
434,1664790,NaN,The inner ring of fencing around the US Capito...,1.0,"inner ring, fencing, US Capitol, removal, thre...",1.0,fencing,0.0,US Capitol
444,2643996,NaN,"Former Cal rugby player Robert Paylor, paralyz...",1.0,"Cal rugby player Robert Paylor, wheelchair, gr...",1.0,Cal rugby player Robert Paylor,0.0,challenges

In [56]:
sampled_data_500[(sampled_data_500['Q3']==1.0) & (sampled_data_500['Q4']==1.0)]['Q4'] = 0

In [57]:
sampled_data_500[(sampled_data_500['Q3']==1.0) & (sampled_data_500['Q4']==1.0)]

Empty DataFrame
Columns: [id, thumbnail, summary, Q1, Q2, Q3, Q3a, Q4, Q4a]
Index: []

In [63]:
sampled_data_500.index

Int64Index([  0,   8,  16,  43,  72,  78, 119, 121, 162, 165, 191, 192, 194,
            206, 207, 210, 214, 225, 229, 233, 236, 238, 240, 247, 249, 257,
            258, 263, 264, 269, 271, 273, 291, 294, 299, 300, 303, 305, 310,
            317, 323, 326, 327, 334, 338, 340, 357, 358, 385, 432, 434, 444],
           dtype='int64')

In [82]:
data = pd.read_excel("annotation_n1000_samples_500.xlsx")
data.loc[[  0,   8,  16,  43,  72,  78, 119, 121, 162, 165, 191, 192, 194,
            206, 207, 210, 214, 225, 229, 233, 236, 238, 240, 247, 249, 257,
            258, 263, 264, 269, 271, 273, 291, 294, 299, 300, 303, 305, 310,
            317, 323, 326, 327, 334, 338, 340, 357, 358, 385, 432, 434, 444], ['Q4']]= 0.0

In [83]:
data[(data['Q3']==1.0) & (data['Q4']==1.0)]

Empty DataFrame
Columns: [id, thumbnail, summary, Q1, Q2, Q3, Q3a, Q4, Q4a]
Index: []

In [86]:
data.to_excel('annotation_n1000_samples_500_2.xlsx')

In [92]:
data = pd.read_excel("annotation_n1000_samples_split3.xlsx")
data[(data['Q3']==1.0) & (data['Q4']==1.0)].index
data.loc[list(data[(data['Q3']==1.0) & (data['Q4']==1.0)].index), ['Q4']] = 0

In [98]:
data = data.drop(labels='Unnamed: 9',axis=1)

In [99]:
data.to_excel('annotation_n1000_samples_split3_2.xlsx')

In [101]:
data = pd.read_excel("annotation_n1000_samples_split4.xlsx")
data[(data['Q3']==1.0) & (data['Q4']==1.0)].index
data.loc[list(data[(data['Q3']==1.0) & (data['Q4']==1.0)].index), ['Q4']] = 0
# data = data.drop(labels='Unnamed: 9',axis=1)
data.to_excel('annotation_n1000_samples_split4_2.xlsx')